version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.6
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.4
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: circle_test
      POSTGRES_HOST: localhost

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix test
      - run:
          name: Running Inch CI documentation tests
          command: |
            MIX_ENV=docs mix deps.get
            MIX_ENV=docs mix inch.report
